version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER}    
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}   
    ports:
      - ${MONGO_PORT}:27017 # host:container
    volumes:
      - mongo_data:/data/db  # Bind the volume to the MongoDB data directory

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_UI_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD}           
      ME_CONFIG_MONGODB_URL: mongodb://${USER}:${PASSWORD}@mongo:27017/ 
      ME_CONFIG_BASICAUTH: "false"                         
    depends_on:
      - mongo

volumes:
  mongo_data:

